### ISSUE TITLE
Attributes without value gives validation errors

### ISSUE THREAD

**Issue by svdoever** [airbnb/hypernova-amp#17]
I need to specify in my AMP html the following:
```
<amp-story standalone
```

This leads to the validation error: 
The attribute 'standalone' in tag 'amp-story' is set to the invalid value 'true'. (see https://www.ampproject.org/docs/reference/components/amp-story)

I tried with:

*  ```<amp-story standalone={null}```
*  ```<amp-story standalone={true}```

But that does not help.

Only fix I could come up with is to use:

```<amp-story standalone="--remove--"```

and remove ```="--remove--"``` before the html is served back.

Any solutions to this issue?

**Comment by svdoever** [comment]
I see it more as a ReactJS issue, there seems to be no way to specify an attribute without a value in ReactJS.
I tried the {null} approach as given in https://stackoverflow.com/questions/37828543/how-to-pass-props-without-value-to-component, but didn't work either. I love your amp-bind approach, so this might be a good addition. would ```attribute="--remove"``` be a good one or any other suggestions?

**Comment by gilbox** [comment]
I can't think of a better naming option but... It turns out that react 16 supports doing `standalone=""` ... is upgrading an option for you?

**Comment by svdoever** [comment]
I'm on 16.3.2, so no problem! I tried it out, and it validates correctly! In the output I still see ```<amp-story standalone=""``` but the AMP validator is happy, and when the AMP validator is happy, I'm happy:-)

**Comment by ljharb** [comment]
I think this actually might be an issue with this package - `<div foo />` which is the same as `<div foo={true} />` should stringify to `<div foo></div>` or `<div foo="foo"></div>`, never `<div foo="true"></div>`.

**Comment by svdoever** [comment]
Wouldn't ```<div foo="" />``` be good enough? Otherwise explicitly write ```<div foo="foo"></div>```...

**Comment by ljharb** [comment]
no, the browser and the standard treats those differently. HTML like `<div foo>` is the same as `<div foo="foo">` but very different from `<div foo="">`.
